# Generated by Django 5.1.4 on 2025-12-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Решена'),
        ),
    ]
